### ISSUE TITLE
Turn off `check.nobs.vs.nRE` lme4-control parameter 

### ISSUE THREAD

**Issue by kliegl** [palday/JellyMe4.jl#30]
In lme4 it is sometimes necessary and justified to explicity set `control=lmerControl(check.nobs.vs.nRE="ignore")`. Currently, when moving such a MixedModel object to R , this triggers: 

`ERROR: REvalError: Error: number of observations (...); the random-effects parameters and the residual variance (or scale parameter) are probably unidentifiable`

 I would appreciate if this control parameter could be turned off or changed to a warning, possibly there are also other parameters of this kind.

**Comment by palday** [comment]
Note to self, the [current set of checks in lme4](https://www.rdocumentation.org/packages/lme4/versions/1.1-23/topics/lmerControl) is:

```R
    check.nobs.vs.rankZ = "ignore",
    check.nobs.vs.nlev = "stop",
    check.nlev.gtreq.5 = "ignore",
    check.nlev.gtr.1 = "stop",
    check.nobs.vs.nRE= "stop",
    check.rankX = c("message+drop.cols", "silent.drop.cols", "warn+drop.cols",
                    "stop.deficient", "ignore"),
    check.scaleX = c("warning","stop","silent.rescale",
                     "message+rescale","warn+rescale","ignore"),
    check.formula.LHS = "stop",
    ## convergence checking options
    check.conv.grad     = .makeCC("warning", tol = 2e-3, relTol = NULL),
    check.conv.singular = .makeCC(action = "message", tol = formals(isSingular)$tol),
    check.conv.hess     = .makeCC(action = "warning", tol = 1e-6),
```
