### ISSUE TITLE
rput issue after package updates

### ISSUE THREAD

**Issue by oricon** [palday/JellyMe4.jl#57]
I'm not sure if this is a RCall or JellyMe4 issue, but I can't use rput after a package update. I get an error about an unexpected '&'. I'm not able to find the & in the data file but I'm not doing anything different than before. Thanks for any guidance on this issue.
```
rt_m1j = (rt_m1, RTdata);
@rput rt_m1j
ERROR: RParseError: Error: unexpected '&'
```
Here is my package list:
```
julia> Pkg.status()
      Status `~/.julia/environments/v1.7/Project.toml
  [69666777] Arrow v2.3.0
  [336ed68f] CSV v0.10.4
  [a93c6f00] DataFrames v1.3.4
  [0b91fe84] DisplayAs v0.1.6
  [c91e804a] Gadfly v1.3.4
  [19ac8677] JellyMe4 v0.2.6
  [ff71e718] MixedModels v4.6.4
  [6f49c342] RCall v0.13.13
  [df47a6cb] RData v0.8.32cb19f9e] StatsKit v0.3.1
```

**Comment by palday** [comment]
Can you provide the model and sample data as a minimum working example of the problem? Or at the least the model summary display from the REPL?

**Comment by oricon** [comment]
Yes here's one of the models (I ran 6 and they all have the same issue).
`rt_m1 = fit(MixedModel, @formula(logRT ~ 1 + alt*prevRew*rewCond*version*platform + (1 | participant)), RTdata, contrasts = Dict(:alt => EffectsCoding(base = "switch"), :rewCond => EffectsCoding(base = "Hi"), :prevRew => EffectsCoding(base = "hi"), :version => EffectsCoding(base = "deterministic"), :platform => EffectsCoding(base = "inlab")))`

and the data (zipped Rda)
[RTdata.Rda.zip](https://github.com/palday/JellyMe4.jl/files/8810537/RTdata.Rda.zip)

I transformed the RT to log with this command:
`RTdata[!, :logRT] .= ( v <= 0. ? 0. : log10(v) for v in RTdata.RT)`

The packages and data were loaded as follows:
```
ENV["LMER"] = "afex &  & lmer_alt"
using MixedModels, RCall, JellyMe4, DataFrames, RData, CSV]

RTdata = load("/Users/joseph.orr/Documents/repositories/VTS_Reward_Training/Rdata/RTdata.Rda");
```

**Comment by palday** [comment]
I think the `ENV` line is wrong. It should be:

```julia
ENV["LMER"] = "afex::lmer_alt"
```

**Comment by oricon** [comment]
Oh man I must have inadvertently done a find & replace that messed that up. Thanks! That would have taken me forever to notice that screw up.
